sudo: false

language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

matrix:
  allow_failures:
    - php: 7.4snapshot
    - php: nightly
  fast_finish: true

env:
  - AMP_DEBUG=true

before_install:
  phpenv config-rm xdebug.ini || echo "No xdebug config.";

install:
  - travis_retry composer update -n --prefer-dist
  - travis_retry composer require php-coveralls/php-coveralls

script:
  - php -dzend.assertions=1 -dassert.exception=1 vendor/bin/phpunit --coverage-text --verbose --coverage-clover build/logs/clover.xml
  - PHP_CS_FIXER_IGNORE_ENV=1 php vendor/bin/php-cs-fixer --diff --dry-run -v fix

after_script:
  - travis_retry vendor/bin/php-coveralls -v

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer
